package com.textureflow.actions;

public enum ActionErrorCode {
    NOTIFICATION_GONE,
    REPLY_NOT_SUPPORTED,
    ACTION_HANDLE_CHANGED,
    EVENT_CHANGED,
    PENDING_INTENT_CANCELLED,
    COMMAND_EXPIRED,
    UNAUTHORIZED,
    DUPLICATE_COMMAND,
    POLICY_BLOCKED,
    DEVICE_OFFLINE,
    NETWORK_ERROR
}
